type Query {
    rooms: [Room!]!
}

type Mutation {
    createRoom(input: CreateRoomInput!): Room!
    joinRoom(id: ID!, user: JoinRoomUserInput!): Room!
}

type Room {
    id: ID!
    name: String!
    users: [User!]!
}

type User {
    id: ID!
    name: String!
}

input CreateRoomInput {
    id: ID!
    name: String!
}

input JoinRoomUserInput {
    id: ID!
    name: String!
}